name: forgejo-CreateIssueComment-Test

on:
  workflow_dispatch:

jobs:
  forgejo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Forgejo API Action
        uses: ./
        with:
          api_url: ${{ vars.FORGEJO_API_URL }}
          token: ${{ secrets.FORGEJO_TOKEN }}
          repository: "owner/repo"
          index: 123
          body: "This is my comment"  #optional
          debug: true                #optional
